### ISSUE TITLE
VISUALIZACIÓN DE COMENTARIOS AL NO ENTREGAR INSUMOS

### ISSUE THREAD

**Issue by LAURABAUTISTA1** [SwissTierrasColombia/ST-Incidents#2]
**Entidad**
 IGAC.

**Prioridad**
MEDIO

**¿La solicitud esta relacionada con algún problema? 
No

**Describir la solución deseada**
En el usuario de gestor, cuando por parte de algún técnico decide no entregar un insumo, se espera que sea visible para el Gestor el comentario de justificación de por qué no se va a entregar.

**Comment by shiido** [comment]
Buenas tardes, se analizó el requerimiento solicitado y se inició el desarrollo que se podrá ver reflejado en el próximo despliegue.
