### ISSUE TITLE
Fallo en Autenticación

### ISSUE THREAD

**Issue by LAURABAUTISTA1** [SwissTierrasColombia/ST-Incidents#4]
**Entidad**
 IGAC.

**Descripción del bug**
El usuario IGAC dmunoz, presenta fallo de autenticación y no puede ingresar al sistema

**¿Cómo simular el error?**
Pasos para reproducir el error:
1. Tras digitar Usuario y contraseña
2. Click en iniciar sesión

**Screenshots**
![WhatsApp Image 2021-03-24 at 15 06 19](https://user-images.githubusercontent.com/80128542/112394265-6888a480-8cca-11eb-86ea-e0800cc27cac.jpeg)

**Comment by shiido** [comment]
Buenos días @LAURABAUTISTA1!

El sistema no deja iniciar sesión con ningún usuario?

**Comment by LAURABAUTISTA1** [comment]
Buen día @shiido,
Yo he podico acceder sin problemas, por ahora solo me reporta ese usuario en particular

**Comment by shiido** [comment]
Lo más probable es que la contraseña no sea la correcta, recordar que las contraseñas son sensibles a mayúsculas y minúsculas y de igual forma se debe verificar que le usuario no se encuentre desactivado en el panel de usuarios del administrador.

Ya se esta trabajando en el componente de recuperar contraseña. Sin embargo dicho componente estará disponible en el siguiente lanzamiento que se realice.

**Comment by LAURABAUTISTA1** [comment]
Jhon, el usuario se encuentra activo (comparto imagén) y alega que es la contraseña que ha utilizado todo el tiempo.
Me podrías indicar que solucion se le puede dar, ya él que requiere atender solicitudes pensientes en el transcurso de estra semana.
![Usuario-Activo](https://user-images.githubusercontent.com/80128542/112510489-776d6680-8d5f-11eb-9963-04ceab1ab06c.png)

**Comment by shiido** [comment]
Laura en ese caso es neceario agendar una reunión técnica para realizar una actualización de la contraseña desde la base de datos.

**Comment by LAURABAUTISTA1** [comment]
Me confirmas con quienes sería la reunión y tu disponibilidad de tiempo para citarla, por favor

**Comment by shiido** [comment]
Realicemos una reunión el día de mañana 26 de marzo en horas de la mañana y solucionamos el problema a través de la base de datos.

**Comment by LAURABAUTISTA1** [comment]
Me confirmas por favor a quien más se requieres que cite a la reunión (tanto de la cooperación como del IGAC)
